#
# Copyright (c) 2013-2016, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

javamail:
  providers:
    smtp-test:
      mail.transport.protocol: smtp
      mail.smtp.host: localhost
      mail.smtp.port: 6457
    imap-test:
      mail.store.protocol: imap
      mail.imap.user: aymen.benhmida@ext.mpsa.com
      mail.imap.host: testserver
      mail.imap.port: 6458
      mail.imap.auth.login.disable: false
      mail.imap.auth.plain.disable: true
    pop3-test:
      mail.store.protocol: pop3
      mail.pop3.user: testuser
      mail.pop3.host: testserver
      mail.pop3.port: 6459

